apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "mcwebui.fullname" . }}
    labels: 
        {{- include "mcwebui.labels" . | nindent 4 }}
data:
    config.json: |-
        {{- $.Files.Get "config.json"  | nindent 6 -}}
